CREATE TABLE adm (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  senha VARCHAR(50) NOT NULL
);

CREATE TABLE ferramentas (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  descricao VARCHAR(255) NOT NULL,
  img VARCHAR(255) NOT NULL,
  status BOOLEAN NOT NULL
)

CREATE TABLE impressora (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  descricao VARCHAR(255) NOT NULL,
  img VARCHAR(255) NOT NULL,
  status BOOLEAN NOT NULL, 
  valor FLOAT NOT NULL
)

CREATE TABLE reserva (
  id SERIAL PRIMARY KEY,
  id_user VARCHAR(36) NOT NULL,
  id_item VARCHAR(36) NOT NULL,
  tipo_item VARCHAR(36) NOT NULL,
  data_reserva DATE NOT NULL,
  hora_inicio TIME NOT NULL,
  hora_fim TIME NOT NULL,
  status_reserva BOOLEAN NOT NULL
)

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  turma VARCHAR(255) NOT NULL,
  senha VARCHAR(255) NOT NULL
)